package com.bps.dto;

// Generated Oct 29, 2014 11:20:20 AM by Hibernate Tools 3.4.0.CR1

/**
 * BpsPointRule generated by hbm2java
 */
public class TpointRule implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO 
	*/ 
	private static final long serialVersionUID = 8236931122060921270L;
	private Integer ruleId;
	private String ruleName;
	private int ruleInput;
	private int ruleOutput;
	private String descr;
	private boolean status;

	public TpointRule() {
	}

	public TpointRule(String ruleName, int ruleInput, int ruleOutput,
			String descr, boolean status) {
		this.ruleName = ruleName;
		this.ruleInput = ruleInput;
		this.ruleOutput = ruleOutput;
		this.descr = descr;
		this.status = status;
	}

	public Integer getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(Integer ruleId) {
		this.ruleId = ruleId;
	}

	public String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}

	public int getRuleInput() {
		return this.ruleInput;
	}

	public void setRuleInput(int ruleInput) {
		this.ruleInput = ruleInput;
	}

	public int getRuleOutput() {
		return this.ruleOutput;
	}

	public void setRuleOutput(int ruleOutput) {
		this.ruleOutput = ruleOutput;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
