package com.bps.dto;

// Generated Oct 29, 2014 11:20:20 AM by Hibernate Tools 3.4.0.CR1

/**
 * BpsPointRuleLog generated by hbm2java
 */
public class TpointRuleLog implements java.io.Serializable {

	/** 
	* @Fields serialVersionUID : TODO 
	*/ 
	private static final long serialVersionUID = -8583109868452114472L;
	private Integer id;
	private int ruleId;
	private String content;
	private short from;
	private long createdTime;

	public TpointRuleLog() {
	}

	public TpointRuleLog(int ruleId, String content, short from,
			long createdTime) {
		this.ruleId = ruleId;
		this.content = content;
		this.from = from;
		this.createdTime = createdTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(int ruleId) {
		this.ruleId = ruleId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public short getFrom() {
		return this.from;
	}

	public void setFrom(short from) {
		this.from = from;
	}

	public long getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(long createdTime) {
		this.createdTime = createdTime;
	}

}
